### PR TITLE
Added German (de) language

### PR DESCRIPTION
**Pull request by Blankjr**
Added German support (language code: de) and executed npm run build successfully

### CODE REVIEW

**Comment by khmyznikov** [comment]
@Blankjr thanks for translation! By the way, _tr.xlf_ means not translation but Turkish, you needed to modify _de.xlf_

**Comment by Blankjr** [comment]
@khmyznikov Your welcome! I guess that happened by trying to recreate the Turkish Pull Request Steps. Thanks for the project!

**Comment by khmyznikov** [comment]
@Blankjr you give me good idea to write steps about adding new locale.

**Comment by Blankjr** [comment]
@khmyznikov I could try creating a Constribution.md, which could be linked into the README.

**Comment by khmyznikov** [comment]
> @khmyznikov I could try creating a Constribution.md, which could be linked into the README.

I think it would be great.

**Pull request merged**
