### PR TITLE
Add Spanish (es) language

### PR DESCRIPTION
**Pull request by jivanf**
Let me know if there's something else that needs to be done :)

### CODE REVIEW

**Comment by khmyznikov** [comment]
Cool, thanks!

**Comment by khmyznikov** [comment]
@jivanf can you test how new es.js bundle version works?

**Comment by jivanf** [comment]
Is there something specific you want to test or just if the translation works? Here's what the latest commit looks like:
Screenshot from 2022-12-19 17-53-50

**Comment by khmyznikov** [comment]
@jivanf no I wonder maybe you [use this file](https://github.com/khmyznikov/pwa-install/blob/main/dist/es/pwa-install.es.js) in your project and just to make sure it's working because after versions upgrades it have smaller size than before.

**Comment by jivanf** [comment]
Alright, just upgraded to the latest commit in my project and I can confirm it works 👍

**Pull request merged**
